Adds campaigns controller
DoSomethingArchive/legacy-website pull request #7050
Opened 2016-09-15 20:32 UTC by deadlybutter

#### What's this PR do?
Adds the campaigns controller standalone

#### How should this be reviewed?
Call the functions!

#### Any background context you want to provide?
See the previous PR https://github.com/DoSomething/phoenix/pull/7047#issuecomment-247443454

#### Relevant tickets
I don't think this fixes any issue actually, but relevant too / assists / unblocks 
#7041 
#7040 
#7042

2016-09-15 20:35 UTC, weerd commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +      staff_pick: args['isStaffPick'] ? +args['isStaffPick'] : 0, // API requires 1/0 instead of true/false
Use the approach @DFurnes [mentioned](https://github.com/DoSomething/phoenix/pull/7047#r79043289)`Number(args['isStaffPick'])`

and add a `@todo` referencing this [bug](https://github.com/DoSomething/phoenix/issues/7049) 😄

2016-09-15 20:39 UTC, weerd commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
Maybe you don't need this `return` if also using a `return` inside the anonymous function dealing with the response?

2016-09-15 20:42 UTC, weerd commented on lib/themes/dosomething/paraneue_dosomething/js/components/CampaignSlide.js
> +}
💃 yay!

2016-09-15 20:42 UTC, weerd requested changes
Just a couple comments on some small things :)

2016-09-15 20:53 UTC, deadlybutter commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
Still getting used to promises, this worked!

2016-09-15 20:53 UTC, deadlybutter commented
@weerd Addressed your review!

2016-09-15 20:57 UTC, DFurnes commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
Wait... sorry to roll in after the fact, but this definitely should have a `return` statement. I'm not even sure how it works without it (the outer `return` returns the Promise from `getCampaigns`, and the inner `return` returns the value to the next step in the Promise chain).

2016-09-15 20:57 UTC, weerd commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
No worries, so am I :)

2016-09-15 20:58 UTC, weerd commented
¡OLÉ! :sheep: it!

2016-09-15 20:58 UTC, weerd approved these changes

2016-09-15 21:01 UTC, deadlybutter commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
👀  well this is odd then

2016-09-15 21:03 UTC, DFurnes commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
How did you test this to verify that removing the `return` still worked? As far as I can tell, block functions don't have implicit returns (only bracketless one-liners do that).

2016-09-15 21:09 UTC, deadlybutter commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
@DFurnes apparently when i called the function it was still the old you, you're def right :facepalm:

2016-09-15 21:10 UTC, deadlybutter commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
i often get this, where i refresh quickly enough the build didnt finish, so i still have the old file

2016-09-15 21:16 UTC, weerd commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
count to 10? 😉 :trollface:

2016-09-15 21:17 UTC, deadlybutter commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
👊

2016-09-15 21:18 UTC, weerd commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
I deserve that. haha

2016-09-15 21:24 UTC, weerd commented on lib/themes/dosomething/paraneue_dosomething/js/campaign/Controller.js
> +    return this.apiClient.get('campaigns', query).then(response => {
Yeah, I forgot we're in the `getCampaigns()` method which should return the data. Alternatively you could put all the logic inside that anonymous function inside a separate method like `processCampaigns()` or something, and then just call that from within the anonymous function? Not a huge deal though.

2016-09-16 14:12 UTC, deadlybutter commented
Looks good to me! 
<img width="432" alt="screen shot 2016-09-16 at 10 12 12 am" src="https://cloud.githubusercontent.com/assets/897368/18588830/1319b44c-7bf6-11e6-9d66-5d72eb7a60cd.png">

2016-09-16 14:42 UTC, weerd commented
Looking good 👍

2016-09-16 14:42 UTC, DFurnes approved these changes

2016-09-16 14:51 UTC, merged