Adds signup button tracking on pitch page
DoSomethingArchive/legacy-website pull request #7098
Opened 2016-09-30 19:39 UTC by deadlybutter

#### What's this PR do?
tell us, what have you changed?

#### How should this be reviewed?
tell us, how can we review, to test that this works

#### Any background context you want to provide?
what else?

#### Relevant tickets
Fixes #

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love.

2016-10-03 17:17 UTC, DFurnes requested changes

2016-10-03 17:17 UTC, DFurnes commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +  if (urlParts[urlParts.length - 1] === 'pitch') {
Have you tested this with a normal account? As far as I  know, `/pitch` is just an override URL for admins.

For example, this is the pitch page URL for Lose Your V-Card (for a logged-out or not signed up user):

[`https://www.dosomething.org/us/campaigns/lose-your-v-card`](https://www.dosomething.org/us/campaigns/lose-your-v-card)

2016-10-03 17:17 UTC, DFurnes commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +    $('#dosomething-signup-form-primary').on('submit', () => {
Is this the ID for both the logged-in "sign up" button form and the logged-out "register and sign up" form? If not, will this still give us the results we're expecting for this test?

2016-10-03 17:19 UTC, deadlybutter commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +  if (urlParts[urlParts.length - 1] === 'pitch') {
Hmm thats a good point, maybe I could go by classname?

`class="campaign campaign--pitch pitch"`

2016-10-03 17:19 UTC, DFurnes commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +  if (urlParts[urlParts.length - 1] === 'pitch') {
That seems like a better idea. :thumbsup:

2016-10-03 17:20 UTC, deadlybutter commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +    $('#dosomething-signup-form-primary').on('submit', () => {
Good catch! `link--campaign-signup-login` is the other ID.

Potentially better option, listen for the button submit under `.header__signup`

2016-10-04 13:57 UTC, DFurnes requested changes

2016-10-04 13:57 UTC, DFurnes commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +    $('.header__signup form, #user-login-form, #user-register-form').on('submit', () => {
Have you tested that `#user-register-form` doesn't trigger this analytics call if there are form validation errors? That may have to be a second event listener on the `Validation:Submitted` event so we don't get false positives from that form (see example usage above, `args` is the form ID).

2016-10-04 14:08 UTC, itsjoekent commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +    $('.header__signup form, #user-login-form, #user-register-form').on('submit', () => {
Looks like it doesn't trigger this event listener, the only GA event I see firing is for the validation error

2016-10-04 14:11 UTC, DFurnes commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +    $('.header__signup form, #user-login-form, #user-register-form').on('submit', () => {
So all working as expected (including actually submitting on successful validation)? If so, merge away!

2016-10-04 14:11 UTC, DFurnes approved these changes

2016-10-04 14:19 UTC, deadlybutter commented on lib/themes/dosomething/paraneue_dosomething/js/utilities/Analytics.js
> +    $('.header__signup form, #user-login-form, #user-register-form').on('submit', () => {
@DFurnes Actually looks like I didn't catch it the first time, I think I'll need to do the Validation Submitted approach

2016-10-04 14:28 UTC, deadlybutter commented
@DFurnes okie, _now_ it works  with 
- new accounts
- logging in
- currently logged in

2016-10-04 14:33 UTC, DFurnes commented
🚢

2016-10-04 14:33 UTC, merged