OpenID Connect: Add ability to queue post-authorization actions.
DoSomethingArchive/legacy-website pull request #7121
Opened 2016-10-12 20:23 UTC by DFurnes

#### What's this PR do?
👷 👷 💻 💧 

#### How should this be reviewed?
🙅‍♂️ 

#### Any background context you want to provide?
🍃

#### Relevant tickets
Fixes #:dog:

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love
- [ ] Post a message in #phoenix if this includes something that causes a rebuild!

2016-10-17 20:27 UTC, weerd requested changes
⚖

2016-10-17 20:27 UTC, weerd commented on lib/modules/dosomething/dosomething_campaign/dosomething_campaign.pages.inc
> -  if (!user_is_logged_in()) {
@DFurnes I found this gem: https://github.com/DoSomething/phoenix/blob/ec89a8484f65841358bccd50042b449ffaa34597/lib/modules/dosomething/dosomething_campaign/dosomething_campaign.module#L404 Seems there _is_ (?) a scenario when an anonymous user would hit the confirmation page?

2016-10-17 20:30 UTC, DFurnes commented on lib/modules/dosomething/dosomething_campaign/dosomething_campaign.pages.inc
> -  if (!user_is_logged_in()) {
Ah, that'd explain it. 😩

2016-10-18 15:53 UTC, weerd commented on lib/modules/dosomething/dosomething_campaign/dosomething_campaign.pages.inc
> +  // If SMS player is anonymous, he button should open the login/register form.
typo `the button...`

2016-10-18 16:38 UTC, weerd commented on lib/modules/dosomething/dosomething_northstar/dosomething_northstar.auth.inc
> +      dosomething_signup_user_signup((int) $target, $user, 'lolol'); // @TODO lololol
set a `source`?

2016-10-18 16:38 UTC, weerd commented on lib/modules/dosomething/dosomething_northstar/dosomething_northstar.auth.inc
> +      dosomething_signup_user_signup((int) $target, $user, 'lolol'); // @TODO lololol
although could be a fun easter egg for the data team :trollface:

2016-10-18 16:43 UTC, DFurnes commented on lib/modules/dosomething/dosomething_northstar/dosomething_northstar.auth.inc
> +      dosomething_signup_user_signup((int) $target, $user, 'lolol'); // @TODO lololol
😈

2016-10-18 16:47 UTC, weerd approved these changes
Our work is awesome. 💃

2016-10-18 16:48 UTC, merged

2016-10-18 16:48 UTC, DFurnes commented
🎉