updates punctuation for translations
DoSomethingArchive/legacy-website pull request #7271
Opened 2017-01-06 16:52 UTC by jessleenyc

#### What's this PR do?
updates po & pot files. added strings to POEditor to account for punctuation, translated and exported the po file to be uploaded. 

#### How should this be reviewed?
...

#### Any background context you want to provide?
...

#### Relevant tickets
Fixes #

#### Checklist
- [ ] Documentation added for new features/changed endpoints.
- [ ] Tested on staging.
- [ ] Pinged a PM if this is a larger PR that would benefit from some additional testing love
- [ ] Post a message in #phoenix if this includes something that causes a rebuild!

2017-01-06 16:55 UTC, jessleenyc commented
@weerd just realized that I have no idea where all the 'month of the year' stuff is coming from?

2017-01-06 21:01 UTC, weerd requested changes
Comment on repeated key/value items. Maybe check in POEditor to see if two exist and likely delete the one w/ the `msgstr \"`??

2017-01-06 21:01 UTC, weerd commented on translations/pos/Phoenix_Portuguese_BR.po
> +
Why are there two of these with one as `Let's Do This!mgstr \"`??

2017-01-06 21:01 UTC, weerd commented on translations/pos/Phoenix_Spanish_MX.po
> +
Same as the Portuguese one... :\

2017-01-06 22:39 UTC, jessleenyc commented
@weerd re-uploaded

2017-01-09 16:10 UTC, weerd approved these changes
👍

2017-01-11 17:38 UTC, merged